### PR TITLE
417: Clarify the process for finding work to do

### PR DESCRIPTION
**Pull request by danhorst**
Formalizing process can be a bit pedantic but I would rather be explicit then leave room for confusion.
What do you think @ndlib/dlt?

[Here is the document as it will be look when merged](https://github.com/ndlib/sipity/blob/417-issue-on-github/CONTRIBUTING.md).

This pull request should not be merged until everyone has weighed in.

### CODE REVIEW

**Comment by jeremyf** [comment]
:+1: The key thing to capture is that we pick from the prioritized list. If we don't know how to act on the prioritized ticket, then seek clarification. In the meantime you can go and find another ticket that might be small in scope.

**Comment by dbrower** [comment]
This looks fine to me.

To be pedantic, I don't like the definition of an issue since:

 * all issues are actionable
 * a question is an issue with a special tag which is not necessarily actionable
 * so a question issue may not be actionable
 * contradiction since all issues are actionable.

I guess this is the main thing that stuck out to me.

**Comment by jeremyf** [comment]
@banurekha @rbalekai Any thoughts? :+1: or :-1: or suggestions?

**Comment by rbalekai** [comment]
:+1:

**Comment by banurekha** [comment]
:+1:

**Comment by cdeluca495** [comment]
Forgive me for asking, but if it is decided that we want to do dev on VM environments instead of local machines, how much of this process will change and what would it look like?

**Comment by jeremyf** [comment]
@cdeluca495 Little of this will change if we do dev on a VM vs. local machine.

**Comment by jeremyf** [comment]
@danhorst Do you have clarifications so we can get this critter reviewed and merged?

**Comment by cdeluca495** [comment]
:+1:

**Pull request merged**
