### PR TITLE
Adding a project code of conduct

### PR DESCRIPTION
**Pull request by danhorst**
[skip ci]

### CODE REVIEW

**Comment by jeremyf** [comment]
:+1:

**Comment by jeremyf** [comment]
@banurekha, @rbalekai, @cdeluca495, @dbrower, please review and give it a :+1: or ask for clarity.

**Comment by rbalekai** [comment]
:+1:

**Comment by cdeluca495** [comment]
:+1:

**Comment by jeremyf** [comment]
ping @banurekha

**Comment by banurekha** [comment]
:+1:

**Pull request merged**
