### PR TITLE
Updating README with explanation of Form/Services

### PR DESCRIPTION
**Pull request by jeremyf**
Answer Why do some repository methods delegate to a service object and
other methods have inline behavior?

[skip ci]

### CODE REVIEW

**Comment by jeremyf** [comment]
@danhorst @dbrower @rbalekai @banurekha Please give a :+1: to ensure everyone has read the changes.

**Comment by banurekha** [comment]
:+1:

**Comment by dbrower** [comment]
I have no idea what `CommandRepository` and `QueryRepository` are. Since they seem to deal with form behavior, I think they are different from Fedora and the "big R" repository.

:+1:

**Comment by rbalekai** [comment]
:+1:

**Comment by danhorst** [comment]
:+1:

**Comment by jeremyf** [comment]
@dbrower The `CommandRepository` and `QueryRepository` are constructs of Sipity. (in `app/repository/sipity`)

**Pull request merged**
