### PR TITLE
Wordsmithing CONTRIBUING & ./scripts/start-issue

### PR DESCRIPTION
**Pull request by jeremyf**
See the comments in the various scripts.
[skip ci]

### CODE REVIEW

**Comment by jeremyf** [comment]
Please review and add any comments. @danhorst @dbrower @rbalekai @cdeluca495 @banurekha 

As stated, the goal is to capture the "moment" when you start working on an issue.

**Comment by danhorst** [comment]
:+1:

**Comment by dbrower** [comment]
:+1: It looks fine to me as a way to create issue branches.

Using it to track time and issues in progress seems like it is duplicating the purpose of the issue tracker. Do issues ever get removed from `STARTED_ISSUES_FILE`, for example? This seems like a data synchronization problem. I don't see the value proposition to justify creating this problem. If the issue tracker is not working, I would address that directly instead of creating another layer of tooling. Just thoughts.

**Comment by rbalekai** [comment]
:+1:

**Comment by jeremyf** [comment]
@dbrower There are a few points in time that we are looking to capture:

1) When an issue is created
2) When someone starts work on an issue
3) When someone finishes work on an issue
4) When the finished work is merged into master (i.e. ready for acceptance)
5) When the finished work is deployed to QA
6) When the finished work is deployed to production

We have information related to an issue being created (i.e. Github API provides that). We know when the first commit is created for the issue (i.e. the first commit in the branch related to the issue).

Knowing when work is started may not be immediately obvious; It is when someone goes in and moves the work from one column to another…and we then check the Github API for that information. Or we can auto-claim an issue by using the script; It provides a convenience method for doing so.

Regarding the data cleanup, yes there might be synchronization issues; I believe the script could do a few more things:

1) ./scripts/finish-issue could close the related issue and remove the line from the .started-issues file.
2) It could auto-assign the branch creator to the issue (allowing for override)

**Comment by dbrower** [comment]
@jeremyf Thanks for the explanation. There is a lot of information you wish to track, and it is stored all over the place. As I see it, the `start-issue` script will allow tracking of item (2).The github issue tracker will track (1) and (4). Jenkins tracks (5) and (6).

My concern was with the creation of process for process's sake. The creation of a process today is a burden on the future. Is the burden worth it? That I don't know. Nor am I claiming it isn't worth it. As far as I know, we are not actively analyzing data points (1), (4), (5), and (6), so it is not clear whether also tracking (2) will add any concrete benefit. In addition to the data synchronization issues, I am curious how it will all work. But I don't object to merging this PR. Let's try it out and see how it goes.

**Comment by jeremyf** [comment]
The goal of the script is that it is cheaper/more efficient to use than
doing what I would normally do by hand.

On Thursday, March 19, 2015, Don Brower <notifications@github.com> wrote:

> @jeremyf <https://github.com/jeremyf> Thanks for the explanation. There
> is a lot of information you wish to track, and it is stored all over the
> place. As I see it, the start-issue script will allow tracking of item
> (2).The github issue tracker will track (1) and (4). Jenkins tracks (5) and
> (6).
>
> My concern was with the creation of process for process's sake. The
> creation of a process today is a burden on the future. Is the burden worth
> it? That I don't know. Nor am I claiming it isn't worth it. As far as I
> know, we are not actively analyzing data points (1), (4), (5), and (6), so
> it is not clear whether also tracking (2) will add any concrete benefit. In
> addition to the data synchronization issues, I am curious how it will all
> work. But I don't object to merging this PR. Let's try it out and see how
> it goes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndlib/sipity/pull/369#issuecomment-83738716>.
>


-- 

Jeremy Friesen
takeonrules.com

**Comment by cdeluca495** [comment]
:+1:

**Comment by banurekha** [comment]
@jeremyf Does it mean Developers need to run this script everytime when they start and finish an issue? Is this in addition to creation new branch for every issue? I am trying to understand the workflow of when new issue is assigned to developer.

**Comment by jeremyf** [comment]
@banurekha Good question.

What @danhorst and I were talking about is knowing when a developer starts a task. So that is the sole purpose of this script. When you are ready to begin, run `./scripts/start-issue <NUMBER>`

`./scripts/start-issue` automates creating your branch, so it is hopefully as cheap as `git branch -co <BRANCH-NAME>` but gives us a crucial bit of data to help determine how long our tasks are taking; Namely a standardized commit message.

When you finish an issue, adding the `closes #<NUMBER>` to your commit message is adequate to say "this is when I finished".

I hope that clarifies. If not, let me know.

**Comment by banurekha** [comment]
That clarifies it.. Thanks for explaining :+1:

**Pull request merged**
