### PR TITLE
Ensuring ETDs have representative file

### PR DESCRIPTION
**Pull request by jeremyf**
## Claiming issue DLTP-796
@6fd5eb385b8b855d6637eaa5a67b7331a1f0314d

$ ./script/start-issue DLTP-796

[skip ci]

## Incorporating representative file in batch export

@d873ac32ea68f7c14bc486d79e0b822a0ca3c184

There are two paths through the associating files:

1) Add a files key/value pair to the ROF and rely on the work filter to
   pick this up.
2) Add an explicit "representative" to the properties key/value pair

I have opted to include both.

See [ROF::Filters::Work](https://github.com/ndlib/rof/blob/da4d2d15c62a78c0fc502d6e94414253dfc2b0df/lib/rof/filters/work.rb#L36)

The following is an example of what is output from a completed Sipity
ETD:

```json
[
  {
    "type": "fobject",
    "pid": "und:o1Rr18nvFmNm0cpOi5eU_A==",
    "af-model": "Etd",
    "metadata": {
      "@context": {
        "bibo": "http://purl.org/ontology/bibo/",
        "dc": "http://purl.org/dc/terms/",
        "ebucore": "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#",
        "foaf": "http://xmlns.com/foaf/0.1/",
        "hydramata-rel": "http://projecthydra.org/ns/relations#",
        "mrel": "http://id.loc.gov/vocabulary/relators/",
        "ms": "http://www.ndltd.org/standards/metadata/etdms/1.1/",
        "nd": "https://library.nd.edu/ns/terms/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "ths": "http://id.loc.gov/vocabulary/relators/",
        "vracore": "http://purl.org/vra/",
        "dc:dateSubmitted": {
          "@type": "http://www.w3.org/2001/XMLSchema#date"
        },
        "dc:created": {
          "@type": "http://www.w3.org/2001/XMLSchema#date"
        },
        "dc:modified": {
          "@type": "http://www.w3.org/2001/XMLSchema#date"
        }
      },
      "dc:title": "My Title",
      "dc:creator": [
        "Jeremy Friesen"
      ],
      "dc:title#alternate": [],
      "dc:subject": [],
      "dc:description#abstract": [
        "<p>An abstract…a great abstract</p>"
      ],
      "dc:rights": [
        "http://creativecommons.org/licenses/by/3.0/us/"
      ],
      "dc:language": [],
      "dc:date": [],
      "dc:dateSubmitted": [
        "2017-02-14"
      ],
      "dc:contributor": [
        {
          "dc:contributor": "Harsh",
          "ms:role": "Research Director"
        }
      ],
      "ms:degree": {
        "ms:name": [
          "Master of Arts"
        ],
        "ms:discipline": [
          "Bioengineering"
        ],
        "ms:level": "Master's Thesis"
      }
    },
    "rels-ext": {
      "@context": {
        "bibo": "http://purl.org/ontology/bibo/",
        "dc": "http://purl.org/dc/terms/",
        "ebucore": "http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#",
        "foaf": "http://xmlns.com/foaf/0.1/",
        "hydramata-rel": "http://projecthydra.org/ns/relations#",
        "mrel": "http://id.loc.gov/vocabulary/relators/",
        "ms": "http://www.ndltd.org/standards/metadata/etdms/1.1/",
        "nd": "https://library.nd.edu/ns/terms/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "ths": "http://id.loc.gov/vocabulary/relators/",
        "vracore": "http://purl.org/vra/",
        "dc:dateSubmitted": {
          "@type": "http://www.w3.org/2001/XMLSchema#date"
        },
        "dc:created": {
          "@type": "http://www.w3.org/2001/XMLSchema#date"
        },
        "dc:modified": {
          "@type": "http://www.w3.org/2001/XMLSchema#date"
        }
      },
      "hydramata-rel:hasEditor": [
        "batch_user_pid"
      ],
      "hydramata-rel:hasEditorGroup": [
        "batch_group_pid"
      ]
    },
    "rights": {
      "read": [
        "jfriesen"
      ],
      "edit": [
        "curate_batch_user"
      ],
      "edit-groups": [
        "batch_group_pid"
      ],
      "read-groups": [
        "public"
      ]
    },
    "files": [
      "und:EM9c-NTpJyBuaMbqgTc29A==",
      "und:haA2DUbUyLS6_mteJXw_3Q=="
    ],
    "properties-meta": {
      "mime-type": "text/xml"
    },
    "properties": "<fields><depositor>curate_batch_user</depositor><representative>und:EM9c-NTpJyBuaMbqgTc29A==</representative></fields>"
  },
  {
    "type": "fobject",
    "pid": "und:EM9c-NTpJyBuaMbqgTc29A==",
    "af-model": "GenericFile",
    "rights": {
      "read": [
        "jfriesen"
      ],
      "edit": [
        "curate_batch_user"
      ],
      "edit-groups": [
        "batch_group_pid"
      ],
      "read-groups": [
        "public"
      ]
    },
    "metadata": {
      "@context": {
        "dc": "http://purl.org/dc/terms/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
      },
      "dc:title": "IMG_20160422_212349.jpg",
      "dc:creator": [
        "jfriesen"
      ],
      "dc:date#created": "2017-02-14Z",
      "dc:modified": "2017-02-14Z"
    },
    "rels-ext": {
      "@context": {
        "dc": "http://purl.org/dc/terms/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
      },
      "hydramata-rel:hasEditor": [
        "batch_user_pid"
      ],
      "hydramata-rel:hasEditorGroup": [
        "batch_group_pid"
      ],
      "isPartOf": [
        "und:o1Rr18nvFmNm0cpOi5eU_A=="
      ]
    },
    "properties-meta": {
      "mime-type": "text/xml"
    },
    "properties": "<fields><depositor>curate_batch_user</depositor></fields>",
    "content-meta": {
      "mime-type": "image/jpeg",
      "label": "IMG_20160422_212349.jpg"
    },
    "content-file": "EM9c-NTpJyBuaMbqgTc29A==-IMG_20160422_212349.jpg"
  },
  {
    "type": "fobject",
    "pid": "und:haA2DUbUyLS6_mteJXw_3Q==",
    "af-model": "GenericFile",
    "rights": {
      "read": [
        "jfriesen"
      ],
      "edit": [
        "curate_batch_user"
      ],
      "edit-groups": [
        "batch_group_pid"
      ],
      "read-groups": [
        "public"
      ]
    },
    "metadata": {
      "@context": {
        "dc": "http://purl.org/dc/terms/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
      },
      "dc:title": "imgres.png",
      "dc:creator": [
        "jfriesen"
      ],
      "dc:date#created": "2017-02-14Z",
      "dc:modified": "2017-02-14Z"
    },
    "rels-ext": {
      "@context": {
        "dc": "http://purl.org/dc/terms/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
      },
      "hydramata-rel:hasEditor": [
        "batch_user_pid"
      ],
      "hydramata-rel:hasEditorGroup": [
        "batch_group_pid"
      ],
      "isPartOf": [
        "und:o1Rr18nvFmNm0cpOi5eU_A=="
      ]
    },
    "properties-meta": {
      "mime-type": "text/xml"
    },
    "properties": "<fields><depositor>curate_batch_user</depositor></fields>",
    "content-meta": {
      "mime-type": "image/png",
      "label": "imgres.png"
    },
    "content-file": "haA2DUbUyLS6_mteJXw_3Q==-imgres.png"
  }
]
```

Closes DLTP-796

### CODE REVIEW

**Comment by dbrower** [comment]
Did you run this through the batch ingest?

I think doing both is confusing. Looking at the batch code, including the `files` section will cause the work translator to completely overwrite the `properties` section. The properties section in the JSON above is missing an `owner` field, btw.

**Comment by jeremyf** [comment]
@dbrower @ruthtillman Who should the owner be? My understanding is that if we set the author of the dissertation as owner they will have edit rights to the object (which is not desired).

I am going to remove the `files` key from the data.

**Comment by ruthtillman** [comment]
Can we make it the ETD Group?

**Comment by jeremyf** [comment]
@ruthtillman I'm uncertain about making the owner a group. It is presently not there, so I'm not interested in adding that behavior to this pull request.

I would prefer to instead create a new JIRA ticket concerning Sipity export owner.

**Comment by jeremyf** [comment]
@dbrower I did not yet send this through the Batch Ingester. I will get that setup for pre-production with my updated PR.

**Comment by jeremyf** [comment]
@dbrower I created an issue related to the owner https://jira.library.nd.edu/browse/DLTP-850

**Comment by dbrower** [comment]
@jeremyf I don't think the `owner` field has any machine actionable meaning in CurateND. I think it is only for our own tracking. (And it is the kind of tracking that Ruth and I have talked about paying more attention to in the future).

**Comment by jeremyf** [comment]
Demonstration of the representative file being associated via Sipity:

https://curatepprd.library.nd.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=qb98mc90798

**Pull request merged**
